runtime: nodejs20  # Ensure you use the correct Node.js version
instance_class: F1  # Choose an instance class based on expected traffic

# Handlers: Define how requests should be routed
handlers:
  - url: /_next/static
    static_dir: .next/static

  - url: /.*
    script: auto

# Environment Variables (optional)
env_variables:
  NODE_ENV: "production"

# Automatic scaling settings (optional)
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  target_throughput_utilization: 0.75


# Ensure App Engine has access to Cloud Build and required APIs
service_account: "absolute-intelligence-390@appspot.gserviceaccount.com"